classai/urls.py
from django.urls import path
from . import views

app_name = "classai"
urlpatterns = [
    path("", views.index, name="index"),
    path("predict/", views.predict, name="predict"),
]

classificatinAI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("classai/", include("classai.urls")),
]

classai/models.py
from django.db import models
import numpy as np
import keras, sys
import tensorflow as tf
from keras.models import load_model
from PIL import Image
import io, base64

graph = tf.compat.v1.get_default_graph()  # tfのノード計算グラフ
class Photo(models.Model):
    image = models.ImageField(upload_to="photos")

    IMAGE_SIZE = 224  # 入力画像サイズ
    MODEL_PATH = "./classai/ml_models/model-1.h5"  # 学習済みモデル
    classes = ["アヒル", "ハト", "白鳥"]  # 教師ラベル
    image_len = len(classes)

    def predict(self):  # 推論・評価
        model=None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")  # カラー指定
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image)/255.0  # 正規化
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted]*100)

            return self.classes[predicted],percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return "data:"+img.file.content_type+";base64,"+base64_img

classai/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"custom-file-input"}))

classai/views.py
from django.shortcuts import render, redirect

# Create your views here.
# ウィンドウに表示する要素を指定する
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def index(request):
    template = loader.get_template("classai/index.html")
    context={"form":PhotoForm()}
    return HttpResponse(template.render(context,request))

def predict(request):
    # エラー処理
    if not request.method=="POST":
        return redirect("classai:index")
    form=PhotoForm(request.POST,request.FILES)
    if not form.is_valid():
        raise ValueError("Formが不正です")
    # メイン処理
    photo=Photo(image=form.cleaned_data["image"])
    predicted,percentage=photo.predict()

    template=loader.get_template("classai/result.html")

    context={
        "photo_name":photo.image.name,
        "photo_data":photo.image_src(),
        "predicted":predicted,
        "percentage":percentage,
    }
    return HttpResponse(template.render(context, request))

classai/templates/classai/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% bootstrap_javascript jquery="full" %}
    <title>画像推定 {% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li>
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    <li>
                        <a class="nav-link disable" href="#" tabindex="-1" aria-disabled="true">Disable</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

classai/templates/classai/index.html
{% extends "classai/base.html" %}
{% block title %}画像判定アプリケーション{% endblock %}
{% block content %}
<div class="alert">
    <td><h1 class="mt-4 mb-5 boder-top">画像推定フォーム</h1></td>
    <br>
    <br>
    <form action="{% url 'classai:predict' %}" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group" >
            <div class="custom-file">
                {{ form.image }}
                <label class="custom-file-label" for="custom-file">
                    推定したいファイルを選択してください。
                </label>
            </div>
        </div>
        <br>
        <div class="btn-wrapper">
            <button type="submit" class="btn btn-secondary btn-lg btn-block">推定を開始します</button>
        </div>
    </form>
</div>
<br></br>

{% endblock %}

classai/templates/classai/result.html
{% extends "classai/base.html" %}
{% block title %}推定結果{% endblock %}

{% block content %}
<div class="result">
  <h4 class="mt-4 mb-5 boder-bottom">画像推定結果</h4>
  <table class="table">
      <p class="body-wrapper">ファイル名:{{photo_name}}</p>

      <img class="preview-img" src={{photo_data}}></img>

      <p class="result">動物名:{{predicted}}</p>
      <p class="result">推定確率:{{percentage}} %</p>

  </table>
  <br>

  <a href="{% url 'classai:index' %}" class="btn btn-primary btn-lg btn-block">選択メニューに戻る</a>

</div>
{% endblock %}